name: Build and Deploy volodb-frontend on Self-Hosted Runner

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: [self-hosted, donbosco] # Use the self-hosted runner with label 'donbosco'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: npm ci # Install dependencies from package-lock.json

      - name: Build the app
        env:
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }} # Use the secret value for VITE_BASE_URL
        run: npm run build # Build the Vite-based Vue app

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist # Upload the build output from the 'dist' directory

  dockerize-and-deploy:
    runs-on: [self-hosted, donbosco] # Use the self-hosted runner with label 'donbosco'
    needs: build # Ensure this job runs only after the build job completes
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: ./dist # Download the build output to the local 'dist' directory

      - name: Build Docker image
        run: |
          # Build the Docker image using the static Dockerfile
          docker build -t volodb-frontend:latest .

      - name: Run Docker container
        run: |
          # Stop and remove any existing container named volodb-frontend
          if [ $(docker ps -q -f name=volodb-frontend) ]; then
            docker stop volodb-frontend
            docker rm volodb-frontend
          fi
          # Run the new Docker container, passing the VITE_BASE_URL environment variable
          docker run -d -p 80:80 --name volodb-frontend \
            -e VITE_BASE_URL=${{ vars.VITE_BASE_URL }} \
            volodb-frontend:latest
